version: '3.9'

services:
  rustapp:
    container_name: rustapp_test
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    container_name: database_test
    image: postgres:12
    environment:
      POSTGRES_USER: teste1
      POSTGRES_PASSWORD: senha_teste
      POSTGRES_DB: rust_db2
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}